USE [master]
GO
/****** Object:  Database [TP4_PASTORINO]    Script Date: 31/7/2022 18:20:18 ******/
CREATE DATABASE [TP4_PASTORINO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP4_PASTORINO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TP4_PASTORINO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TP4_PASTORINO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TP4_PASTORINO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TP4_PASTORINO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP4_PASTORINO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TP4_PASTORINO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET ARITHABORT OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TP4_PASTORINO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TP4_PASTORINO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TP4_PASTORINO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TP4_PASTORINO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET RECOVERY FULL 
GO
ALTER DATABASE [TP4_PASTORINO] SET  MULTI_USER 
GO
ALTER DATABASE [TP4_PASTORINO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TP4_PASTORINO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TP4_PASTORINO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TP4_PASTORINO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TP4_PASTORINO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TP4_PASTORINO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TP4_PASTORINO', N'ON'
GO
ALTER DATABASE [TP4_PASTORINO] SET QUERY_STORE = OFF
GO
USE [TP4_PASTORINO]
GO
/****** Object:  Table [dbo].[ALUMNOS]    Script Date: 31/7/2022 18:20:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALUMNOS](
	[nombre] [varchar](50) NOT NULL,
	[apellido] [varchar](50) NOT NULL,
	[dni] [int] NOT NULL,
	[correo] [varchar](70) NOT NULL,
	[estado] [varchar](50) NOT NULL,
	[idPlanAdquirido] [int] NOT NULL,
 CONSTRAINT [PK_dbo.Alumnos] PRIMARY KEY CLUSTERED 
(
	[dni] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[ALUMNOS] ([nombre], [apellido], [dni], [correo], [estado], [idPlanAdquirido]) VALUES (N'Diego', N'Maradona', 14378854, N'eldiegote@gmail.com', N'0', 5)
GO
INSERT [dbo].[ALUMNOS] ([nombre], [apellido], [dni], [correo], [estado], [idPlanAdquirido]) VALUES (N'Radamel', N'Falcao', 33333333, N'falcao123@hotmail.com', N'0', 3)
GO
INSERT [dbo].[ALUMNOS] ([nombre], [apellido], [dni], [correo], [estado], [idPlanAdquirido]) VALUES (N'Lionel', N'Messi', 35458981, N'leomessi@gmail.com', N'0', 2)
GO
INSERT [dbo].[ALUMNOS] ([nombre], [apellido], [dni], [correo], [estado], [idPlanAdquirido]) VALUES (N'Gianluca', N'Pastorino', 40936456, N'gianlucapastorino1@gmail.com', N'0', 4)
GO
INSERT [dbo].[ALUMNOS] ([nombre], [apellido], [dni], [correo], [estado], [idPlanAdquirido]) VALUES (N'John', N'Lennon', 60000000, N'lennon@beatles.com', N'1', -2147483648)
GO
USE [master]
GO
ALTER DATABASE [TP4_PASTORINO] SET  READ_WRITE 
GO
